# Generated by Django 2.2.1 on 2019-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Limpeza', 'Limpeza'), ('Alimentação', 'Alimentação'), ('Higiene Pessoal', 'Higiene Pessoal'), ('Outro', 'Outro')], max_length=30)),
                ('unidade_medida', models.CharField(choices=[('Un', 'Unidades'), ('Pct', 'Pacotes'), ('Kg', 'Peso')], max_length=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_minima_desejada', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('ultima_data_saida', models.DateField(blank=True, null=True)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ManyToManyField(to='Dispensa.Item')),
            ],
        ),
    ]
