# Generated by Django 2.2.1 on 2019-05-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dispensa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='morador',
        ),
    ]
